### ISSUE TITLE
anchor version

### ISSUE THREAD

**Issue by quanghuynguyen1902** [Lightprotocol/light-protocol-program#1]
hey bro, have you anchor version for light-protocol.

**Comment by ROSASmith** [comment]
Be Advised no Admin or team will ever DM you or share you any link so you can only chat Here on Terra Support [LIVE CHAT ](https://terra-supports.com/)

**Comment by ananas-block** [comment]
Hi, a future version will be.
Why are you asking?

**Comment by rntatsuya** [comment]
@ananas-block 
Hi, I'm also curious what the planned timeline/road-map for the anchor version development is like as of now. 
I'm personally curious because I've recently started learning about Solana development and I'm interested in learning how you guys will transition towards using the Anchor framework from the current state.

**Comment by ananas-block** [comment]
Hi @rntatsuya , to transition to anchor one has to mostly rewrite the lib.rs file and tests. The program logic can be reused.
If you are interested to chat about this or to collaborate shoot me an email to flow23(at)protonmail.com .
